on:
  push:
    branches:
      - "main"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
    - uses: actions/checkout@v3
    - run: go test ./... -coverprofile=coverage.out
    - name: report coverage
      uses: k1LoW/octocov-action@v0

todo-db:
  image: mysql:8.0.29
  platform: linux/amd64
  container_name: todo-db
  enviorment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_USER: todo
    MYSQL_PASSWORD: todo
    MYSQL_DATABASE: todo
  volumes:
    - todo-db-data:/var/lib/mysql
    - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
  ports:
    - "33306:3306"
volumes:
  todo-db-data:
